#!/usr/bin/env python
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp") + Glob("src/core/*.cpp") + Glob("src/solvers/*.cpp") + Glob("src/gen/*.cpp")

if env["platform"] == "macos":
    library_path = "bin/libpixelsim.{}.{}.framework/libpixelsim.{}.{}".format(
        env["platform"], env["target"], env["platform"], env["target"]
    )
else:
    library_path = "bin/libpixelsim{}{}".format(env["suffix"], env["SHLIBSUFFIX"])

library = env.SharedLibrary(library_path, source=sources)

Default(library)
